from datetime import datetime
from typing import Any, List, Dict, Tuple
from src.prescription.schemas import PrescriptionSafetyReport
from src.prescription.contextual.contextual_schema import (
    ContextualStabilityProfile,
    ScenarioProfile,
    ScenarioContext
)
from src.prescription.contextual.scenario_generator import ScenarioGenerator
from src.prescription.contextual.scenario_evaluator import ScenarioEvaluator
from src.prescription.contextual.metrics_analyzer import MetricsAnalyzer
from src.prescription.contextual.stability_interpreter import StabilityInterpreter

class ContextualStabilityAggregator:
    @staticmethod
    def analyze(
        report: PrescriptionSafetyReport,
        structural_analysis: Any,
        reasoner: Any
    ) -> ContextualStabilityProfile:
        analysis_id = report.prescription_id
        generated_at = datetime.now().isoformat()

        # 1. Generate all scenario contexts
        contexts = ScenarioGenerator.generate_all(report, structural_analysis)

        scenarios: List[ScenarioProfile] = []
        scenario_map: Dict[str, Tuple[ScenarioProfile, Any, Any]] = {}

        # 2. Evaluate each scenario
        # Save baseline references separately for metrics
        baseline_profile = None
        baseline_struct = None
        baseline_intel = None

        for ctx in contexts:
            profile, struct, intel = ScenarioEvaluator.evaluate(ctx, report, reasoner)
            scenarios.append(profile)
            scenario_map[ctx.scenario_id] = (profile, struct, intel)

            if ctx.scenario_id == "SCENARIO_BASELINE":
                baseline_profile = profile
                baseline_struct = struct
                baseline_intel = intel

        # Fallback if baseline scenario missing (should not happen)
        if not baseline_profile:
            raise ValueError("SCENARIO_BASELINE was not generated by ScenarioGenerator.")

        # 3. Analyze cross-scenario metrics
        stability, persistences, sensitivity, dependencies, global_stability = MetricsAnalyzer.analyze(
            scenarios=scenarios,
            baseline_profile=baseline_profile,
            baseline_struct=baseline_struct,
            baseline_intel=baseline_intel,
            scenario_map=scenario_map
        )

        # 4. Construct ContextualStabilityProfile
        profile = ContextualStabilityProfile(
            analysis_id=analysis_id,
            generated_at=generated_at,
            scenarios=scenarios,
            evidence_stability=stability,
            signal_persistences=persistences,
            context_sensitivity=sensitivity,
            drug_dependencies=dependencies,
            interpretation_stability=global_stability,
            summary_narrative=""
        )

        # 5. Populate executive summary narrative text
        profile.summary_narrative = StabilityInterpreter.generate(profile)

        return profile
